export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";

export const SET_AUTH_USER = 'SET_AUTH_USER';
export const UPDATE_AUTH_USER = 'UPDATE_AUTH_USER';

export const REQUEST_PROPERTIES_PAGE = 'REQUEST_PROPERTIES_PAGE';
export const RECEIVE_PROPERTIES_PAGE = 'RECEIVE_PROPERTIES_PAGE';

export const SET_ACTIVE_PROPERTY = 'SET_ACTIVE_PROPERTY';

export const SET_USER_FUNCTION = 'SET_USER_FUNCTION';
