export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";

export const SET_AUTH_USER = 'SET_AUTH_USER';
export const UPDATE_AUTH_USER = 'UPDATE_AUTH_USER';

export const REQUEST_PROPERTIES_PAGE = 'REQUEST_PROPERTIES_PAGE';
export const RECEIVE_PROPERTIES_PAGE = 'RECEIVE_PROPERTIES_PAGE';

export const RECEIVE_ACTIVE_PROPERTY = 'SET_ACTIVE_PROPERTY';
export const REQUEST_ACTIVE_PROPERTY = 'REQUEST_ACTIVE_PROPERTY';

export const SET_ACTIVE_PROPERTY_LISTING = 'SET_ACTIVE_PROPERTY_LISTING';
export const SET_ACTIVE_PROPERTY_APPLICATION = 'SET_ACTIVE_PROPERTY_APPLICATION';
export const SET_ACTIVE_PROPERTY_LEASE = 'SET_ACTIVE_PROPERTY_LEASE';
export const SET_ACTIVE_PROPERTY_PAYMENT = 'SET_ACTIVE_PROPERTY_PAYMENT';
export const SET_ACTIVE_PROPERTY_MAINTENANCE = 'SET_ACTIVE_PROPERTY_MAINTENANCE';

export const SET_USER_FUNCTION = 'SET_USER_FUNCTION';
