/*landlord*/
export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";

export const SET_AUTH_USER = 'SET_AUTH_USER';
export const UPDATE_AUTH_USER = 'UPDATE_AUTH_USER';

export const REQUEST_PROPERTIES_PAGE = 'REQUEST_PROPERTIES_PAGE';
export const RECEIVE_PROPERTIES_PAGE = 'RECEIVE_PROPERTIES_PAGE';

export const RECEIVE_ACTIVE_PROPERTY = 'SET_ACTIVE_PROPERTY';
export const REQUEST_ACTIVE_PROPERTY = 'REQUEST_ACTIVE_PROPERTY';

export const SET_ACTIVE_PROPERTY_LISTING = 'SET_ACTIVE_PROPERTY_LISTING';
export const SET_ACTIVE_PROPERTY_APPLICATION = 'SET_ACTIVE_PROPERTY_APPLICATION';
export const SET_ACTIVE_PROPERTY_LEASE = 'SET_ACTIVE_PROPERTY_LEASE';
export const SET_ACTIVE_PROPERTY_PAYMENT = 'SET_ACTIVE_PROPERTY_PAYMENT';
export const SET_ACTIVE_PROPERTY_MAINTENANCE = 'SET_ACTIVE_PROPERTY_MAINTENANCE';

export const SET_USER_FUNCTION = 'SET_USER_FUNCTION';
/*tenants */

export const LOAD_TENANT_SUCCESS = 'LOAD_TENANT_SUCCESS';
export const LOAD_SPCIFIC_TENANT_SUCCESS = 'LOAD_SPECIFIC_TENANT_SUCCESS';
export const PATCH_SPCIFIC_TENANT_SUCCESS = 'PATCH_SPECIFIC_TENANT_SUCCESS';
export const DELETE_SPCIFIC_TENANT_SUCCESS = 'DELETE_SPECIFIC_TENANT_SUCCESS';

export const SET_TENANT_GENERAL = 'SET_TENANT_GENERAL';
export const SET_TENANT_BIO = 'SET_TENANT_BIO';
export const SET_TENANT_RESIDENCE = 'SET_TENANT_RESIDENCE';
export const SET_TENANT_IMMIGRATION = 'SET_TENANT_IMMIGRATION';
export const SET_TENANT_EMPLOYMENT = 'SET_TENANT_EMPLOYMENT';

export const LIST_TENANT_GENERAL = 'SET_TENANT_GENERAL';
export const LIST_TENANT_BIO = 'SET_TENANT_BIO';
export const LIST_TENANT_RESIDENCE = 'LIST_TENANT_RESIDENCE';
export const LIST_TENANT_IMMIGRATION = 'LIST_TENANT_IMMIGRATION';
export const LIST_TENANT_EMPLOYMENT = 'LIST_TENANT_EMPLOYMENT';


export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
export const ERROR_LOADING = 'ERROR_LOADING';